version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    open-pull-requests-limit: 30
    target-branch: "jetty-12.0.x"
    schedule:
      interval: "daily"
    # Associate with milestone 12.0.x
    milestone: 8
    commit-message:
      prefix: "[12.0.x] "
    groups:
      maven:
        applies-to: security-updates
        patterns:
          - "*"

  - package-ecosystem: "maven"
    directory: "/"
    open-pull-requests-limit: 30
    target-branch: "jetty-12.1.x"
    schedule:
      interval: "daily"
    # Associate with milestone 12.1.x
    milestone: 89
    commit-message:
      prefix: "[12.1.x] "
    groups:
      maven:
        applies-to: security-updates
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
